name: pawpath
description: A Flutter app to track your dog walks.

publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  storybook_flutter: ^0.14.0
  device_frame: ^1.1.0
  gap: ^3.0.1
  go_router: ^10.1.2
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
